method: grid
metric:
  goal: maximize
  name: best_dev_metric_f
parameters:
  # n_sample:
  #   value: 0
  # seed:
  #   values:
  #   - 42
  #   - 1314
  #   - 3407
  # dropout:
  #   values:
  #   - 0.1
  #   - 0.3
  #   - 0.5
  # cl_type:
  #   values:
  #   - euclidean
  #   - cosine
  cl_temperature:
    values:
    - 0.05
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 1.0
  